replicaCount: 1

image:
  repository: myoung34/github-runner
  tag: latest
  pullPolicy: Always

github:
  repoUrl: https://github.com/milan-bud/k8s-homelab
  runnerWorkdir: "/tmp/runner"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
