apiVersion: v2
name: observability
description: A Helm chart for Kubernetes Monitoring
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
