apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-runner
  template:
    metadata:
      labels:
        app: cicd-runner
    spec:
      containers:
      - name: runner
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        env:
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cicd-runner-secret
              key: ACCESS_TOKEN
        - name: REPO_URL
          value: {{ .Values.github.repoUrl | quote }} 
        - name: RUNNER_WORKDIR
          value: {{ .Values.github.runnerWorkdir | quote }}
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
