apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-runner
  template:
    metadata:
      labels:
        app: cicd-runner
    spec:
      containers:
      - name: runner
        image: {{ .Values.image }}
        env:
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cicd-runner-secret
              key: ACCESS_TOKEN
        - name: REPO_URL
          value: {{ .Values.repoUrl | quote }}
        - name: RUNNER_WORKDIR
          value: {{ .Values.runnerWorkdir | quote }}
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
