n8n:
  extraEnv:
    GENERIC_TIMEZONE:
      value: "Europe/Zagreb"
    WEBHOOK_URL:
      value: "http://10.218.241.217:5678/"
    N8N_SECURE_COOKIE:
      value: "false" 
    
  persistence:
    enabled: true
    type: dynamic
    size: 1Gi
    accessModes:
      - ReadWriteOnce

  serviceAccount:
    create: false
    name: "n8n-sa"
