n8n:
  extraEnv:
    - name: GENERIC_TIMEZONE
      value: "Europe/Zagreb"
    - name: WEBHOOK_URL
      value: "http://localhost:5678/"
    - name: N8N_SECURE_COOKIE
      value: "false" 
    
  persistence:
    enabled: true
    type: dynamic
    size: 1Gi
    accessModes:
      - ReadWriteOnce

  serviceAccount:
    create: false
    name: "n8n-sa"
