apiVersion: v2
name: keda 
type: application
version: 1.0.0

dependencies:
  - name: keda
    # Using ^ to allow new scalers/features within the v2 lifecycle
    version: "^2.19.0" 
    repository: https://kedacore.github.io/charts
