hotel_app:
  replicaCount: 1
  image:
    repository: hotel-app
    tag: v1.0.0
    pullPolicy: IfNotPresent

  ingress:
    host: "test.lab.local"
  
  database:
    host: "postgres.test.svc.cluster.local"
    secretName: "hotel-db-secret"
  
  redis:
    host: "redis-master.redis.svc.cluster.local"
    port: 6379

  keda:
    minReplicas: 0
    maxReplicas: 2
    sessionsPerPod: "10"
